"""Kaizo trainer parties and species data, backed by data/trainers.json and
data/species.csv (generated by tools/gen_trainers.py from the HZLA dataset
and the pokeplatinum decomp).
"""
from __future__ import annotations

import csv
import json
from functools import lru_cache
from pathlib import Path

from . import scoring
from .names import UnknownName, squash
from .state import Pokemon
from .stats import compute_stats

_DATA = Path(__file__).resolve().parent.parent / "data"

#: The game's AI flag bit order (pokeplatinum generated/ai_flags.txt).
AI_FLAG_BITS = (
    "basic", "evaluate_attacks", "expert", "setup_first_turn", "risky",
    "prio_damage", "baton_pass", "tag_strategy", "check_hp", "weather",
    "harassment",
)


@lru_cache(maxsize=1)
def _species() -> dict[str, dict]:
    rows = {}
    with (_DATA / "species.csv").open() as fh:
        for row in csv.DictReader(fh):
            rows[squash(row["Name"])] = row
    return rows


@lru_cache(maxsize=1)
def _trainers() -> list[dict]:
    return json.loads((_DATA / "trainers.json").read_text())


def species_row(name: str) -> dict:
    row = _species().get(squash(name))
    if row is None:
        raise UnknownName(f"unknown species {name!r}")
    return row


def species_names() -> list[str]:
    return [row["Name"] for row in _species().values()]


def trainer_index() -> list[dict]:
    """Summary rows for the trainer picker."""
    return [{
        "id": t["id"],
        "name": t["name"],
        "location": t["location"],
        "battle_type": t["battle_type"],
        "party": [{"species": p["species"], "level": p["level"]}
                  for p in t["party"]],
    } for t in _trainers()]


def load_trainer(tr_id: int) -> dict:
    for t in _trainers():
        if t["id"] == tr_id:
            return t
    raise UnknownName(f"unknown trainer id {tr_id}")


def decode_ai_flags(mask: int) -> tuple[set[str], set[str]]:
    """(engine-supported flag ids, unsupported flag names) for an ai bitmask."""
    supported, unsupported = set(), set()
    for bit, flag in enumerate(AI_FLAG_BITS):
        if mask & (1 << bit):
            (supported if flag in scoring.FLAG_MODULES else unsupported).add(flag)
    return supported, unsupported


def build_pokemon(entry: dict) -> Pokemon:
    """A state.Pokemon from a trainers.json party entry (trainer EVs are 0)."""
    row = species_row(entry["species"])
    base = {"hp": int(row["HP"]), "atk": int(row["Atk"]), "def": int(row["Def"]),
            "spa": int(row["SpA"]), "spd": int(row["SpD"]), "spe": int(row["Spe"])}
    ivs = {"hp": entry["ivs"]["hp"], "atk": entry["ivs"]["at"],
           "def": entry["ivs"]["df"], "spa": entry["ivs"]["sa"],
           "spd": entry["ivs"]["sd"], "spe": entry["ivs"]["sp"]}
    zero_evs = {k: 0 for k in ivs}
    max_hp, stats = compute_stats(base, ivs, zero_evs, entry["level"],
                                  entry["nature"])
    types = (row["Type1"],) if not row["Type2"] else (row["Type1"], row["Type2"])
    return Pokemon(
        species=entry["species"],
        level=entry["level"],
        ability=entry["ability"],
        item=entry["item"],
        types=types,
        stats=stats,
        max_hp=max_hp,
        current_hp=max_hp,
        gender=entry["gender"],
        moves=list(entry["moves"]),
        friendship=255,
        weight_hg=int(row["WeightHg"]),
    )
